name: kaggle_competition_venv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - scikit-learn=0.24.2
  - auto-sklearn=0.15.0
  - pandas
  - numpy
  - matplotlib
  - pip
  - pip:
      - datacleaner
